# Database Configuration
db.url=jdbc:mysql://localhost:3306/OnlineBankingDB
# will update after review 
db.username=your_db_username                    
db.password=your_db_password
db.driver=com.mysql.cj.jdbc.Driver


# SQL Script Paths
db.schema.script=src/main/resources/schema.sql
db.data.script=src/main/resources/data.sql
